### ISSUE TITLE
Missing the JsonListener.h ?

### ISSUE THREAD

**Issue by Robiv8** [garretlab/DarkSky_uOLED-128-G2#1]
Hallo,
I'm trying to recreate it with an ESP8266 and Waveshare 1.5inch RGB OLED Display Module 128x128 pixel 16-bit High Color SPI Interface with Embedded Controller.
When compiling comes the message:
JsonListener.h: No such file or directory
Where can I get these?
Thank you very much.

**Comment by garretlab** [comment]
You can get it from library manager of Arduino IDE.

From Arduino IDE, choose Sketch > Include Library > Manage Libraries, or, Crrl+shift+i.

Then, filter with "json streaming parser".

**Comment by Robiv8** [comment]
Thank you very much. Found it!
i have one more issue
'getLocalTime' was not declared in this scope

**Comment by garretlab** [comment]
This sketch is for Arduino core for ESP32 WiFi.
I needed to change the sketch for the release v1.0.1 and I committed it.

The getLocalTime() is declared in the Arduino.h.
How about inserting #include "Arduino.h" ?

**Comment by Robiv8** [comment]
Thanks, I will test it in a view days.
I try this with a 1.5 "Waveshare RGB OLED module and the U8g2 library.

**Comment by garretlab** [comment]
Close.

**Comment by garretlab** [comment]
Close.
